SET NAMES UTF8;
DROP DATABASE IF EXISTS jd;
CREATE DATABASE jd CHARSET=UTF8;
USE jd;
CREATE TABLE dept(
    did INT PRIMARY KEY,
    dname VARCHAR(32)
);
INSERT INTO dept VALUES(10,'研发部');
INSERT INTO dept VALUES(20,'研发部');
INSERT INTO dept VALUES(30,'市场部');

CREATE TABLE emp(
   eid INT PRIMARY KEY,
   ename VARCHAR(6),
   deptId INT,
   FOREIGN KEY (deptId) REFERENCES dept(did)
);
INSERT INTO emp VALUES(101,'TOM',20);
INSERT INTO emp VALUES(102,'JERRY',20);
INSERT INTO emp VALUES(103,'MARRY',20);
INSERT INTO emp VALUES(104,'TONY',20);
INSERT INTO emp VALUES(105,'LINI',30);
